# Generated by Django 5.2.7 on 2025-10-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('works', 'Ваши работы'), ('review', 'Обзоры')], default='news', max_length=20, verbose_name='Категория'),
        ),
    ]
